"""empty message

Revision ID: 3dd7ff85f7e8
Revises: 7736471c5fc7
Create Date: 2021-02-16 14:38:08.920397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd7ff85f7e8'
down_revision = '7736471c5fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etat_avancement',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('nbEspPubRec', sa.Integer(), nullable=True),
    sa.Column('nbEspPubBapt', sa.Integer(), nullable=True),
    sa.Column('nbEspPubNonBapt', sa.Integer(), nullable=True),
    sa.Column('nbBapProp', sa.Integer(), nullable=True),
    sa.Column('nbRueBoulVois', sa.Integer(), nullable=True),
    sa.Column('nbCiteAglo', sa.Integer(), nullable=True),
    sa.Column('nbJardPlace', sa.Integer(), nullable=True),
    sa.Column('nbMonumHist', sa.Integer(), nullable=True),
    sa.Column('nbInstImmo', sa.Integer(), nullable=True),
    sa.Column('nbAutre', sa.Integer(), nullable=True),
    sa.Column('nbBaptAppr', sa.Integer(), nullable=True),
    sa.Column('pourcBaptAppr', sa.Float(), nullable=True),
    sa.Column('sommeEspPubBaptEtBaptAppr', sa.Integer(), nullable=True),
    sa.Column('pourc', sa.Float(), nullable=True),
    sa.Column('sommeEspPubBaptEtBaptApprouvees', sa.Integer(), nullable=True),
    sa.Column('code_commune', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['code_commune'], ['commune.code_commune'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etat_avancement')
    # ### end Alembic commands ###
