"""empty message

Revision ID: 63f1dec73dd6
Revises: 3e118fb0d8af
Create Date: 2021-02-16 15:02:33.634250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63f1dec73dd6'
down_revision = '3e118fb0d8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etat_avancement', sa.Column('pourcBapt', sa.Float(), nullable=True))
    op.drop_column('etat_avancement', 'pourc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etat_avancement', sa.Column('pourc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('etat_avancement', 'pourcBapt')
    # ### end Alembic commands ###
