"""empty message

Revision ID: 9534f39a77d8
Revises: 12e8cca11770
Create Date: 2021-03-02 14:39:17.318486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9534f39a77d8'
down_revision = '12e8cca11770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commune', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commune', 'type')
    # ### end Alembic commands ###
