"""empty message

Revision ID: d6883b82b7c3
Revises: 990016cd55d5
Create Date: 2021-03-21 12:43:35.536526

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6883b82b7c3'
down_revision = '990016cd55d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geoms',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('geom_id', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('reference_object',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('addressComponent_id', sa.Integer(), nullable=True),
    sa.Column('geoms_uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['addressComponent_id'], ['address_component.id'], ),
    sa.ForeignKeyConstraint(['geoms_uuid'], ['geoms.uuid'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_object')
    op.drop_table('geoms')
    # ### end Alembic commands ###
