"""empty message

Revision ID: ebc7452c997b
Revises: 9534f39a77d8
Create Date: 2021-03-03 09:58:26.155625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc7452c997b'
down_revision = '9534f39a77d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commune', 'code_commune',
                    nullable=False, new_column_name='pk')
    op.add_column('decision', sa.Column(
        'pk_commune', sa.String(), nullable=True))
    op.drop_constraint('decision_code_commune_fkey',
                       'decision', type_='foreignkey')
    op.create_foreign_key(None, 'decision', 'commune', ['pk_commune'], ['pk'])
    op.drop_column('decision', 'code_commune')
    op.add_column('decision_commune', sa.Column(
        'pk_commune', sa.String(), nullable=False))
    op.drop_constraint('decision_commune_code_commune_fkey',
                       'decision_commune', type_='foreignkey')
    op.create_foreign_key(None, 'decision_commune',
                          'commune', ['pk_commune'], ['pk'])
    op.drop_column('decision_commune', 'code_commune')
    op.add_column('etat_avancement', sa.Column(
        'pk_commune', sa.String(), nullable=True))
    op.drop_constraint('etat_avancement_code_commune_fkey',
                       'etat_avancement', type_='foreignkey')
    op.create_foreign_key(None, 'etat_avancement',
                          'commune', ['pk_commune'], ['pk'])
    op.drop_column('etat_avancement', 'code_commune')
    op.drop_constraint('user_affectation_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'commune', ['affectation_id'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_affectation_id_fkey', 'user', 'commune', [
                          'affectation_id'], ['code_commune'])
    op.add_column('etat_avancement', sa.Column('code_commune',
                                               sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'etat_avancement', type_='foreignkey')
    op.create_foreign_key('etat_avancement_code_commune_fkey',
                          'etat_avancement', 'commune', ['code_commune'], ['code_commune'])
    op.drop_column('etat_avancement', 'pk_commune')
    op.add_column('decision_commune', sa.Column('code_commune',
                                                sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'decision_commune', type_='foreignkey')
    op.create_foreign_key('decision_commune_code_commune_fkey',
                          'decision_commune', 'commune', ['code_commune'], ['code_commune'])
    op.drop_column('decision_commune', 'pk_commune')
    op.add_column('decision', sa.Column('code_commune',
                                        sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'decision', type_='foreignkey')
    op.create_foreign_key('decision_code_commune_fkey', 'decision', 'commune', [
                          'code_commune'], ['code_commune'])
    op.drop_column('decision', 'pk_commune')
    op.add_column('commune', sa.Column('code_commune',
                                       sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('commune', 'pk')
    # ### end Alembic commands ###
