"""empty message

Revision ID: 386c90b50e3f
Revises: d6883b82b7c3
Create Date: 2021-03-28 14:51:15.804687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '386c90b50e3f'
down_revision = 'd6883b82b7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=True))
    op.create_index(op.f('ix_user_api_key'), 'user', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_key'), table_name='user')
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
