"""empty message

Revision ID: 3e118fb0d8af
Revises: 3dd7ff85f7e8
Create Date: 2021-02-16 15:01:10.499648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e118fb0d8af'
down_revision = '3dd7ff85f7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etat_avancement', sa.Column('entrPlaqNomFab', sa.String(), nullable=True))
    op.add_column('etat_avancement', sa.Column('entrPlaqNomInst', sa.String(), nullable=True))
    op.add_column('etat_avancement', sa.Column('entrPlaqNumFab', sa.String(), nullable=True))
    op.add_column('etat_avancement', sa.Column('entrPlaqNumInst', sa.String(), nullable=True))
    op.add_column('etat_avancement', sa.Column('nbPlaqNomInst', sa.Integer(), nullable=True))
    op.add_column('etat_avancement', sa.Column('nbPlaqNomNonInst', sa.Integer(), nullable=True))
    op.add_column('etat_avancement', sa.Column('nbPlaqNomPrevParComm', sa.Integer(), nullable=True))
    op.add_column('etat_avancement', sa.Column('nbPlaqNumInst', sa.Integer(), nullable=True))
    op.add_column('etat_avancement', sa.Column('nbPlaqNumNonInst', sa.Integer(), nullable=True))
    op.add_column('etat_avancement', sa.Column('nbPlaqNumPrevParComm', sa.Integer(), nullable=True))
    op.add_column('etat_avancement', sa.Column('pourcInstPlaqNom', sa.Float(), nullable=True))
    op.add_column('etat_avancement', sa.Column('pourcInstPlaqNum', sa.Float(), nullable=True))
    op.drop_column('etat_avancement', 'sommeEspPubBaptEtBaptApprouvees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etat_avancement', sa.Column('sommeEspPubBaptEtBaptApprouvees', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('etat_avancement', 'pourcInstPlaqNum')
    op.drop_column('etat_avancement', 'pourcInstPlaqNom')
    op.drop_column('etat_avancement', 'nbPlaqNumPrevParComm')
    op.drop_column('etat_avancement', 'nbPlaqNumNonInst')
    op.drop_column('etat_avancement', 'nbPlaqNumInst')
    op.drop_column('etat_avancement', 'nbPlaqNomPrevParComm')
    op.drop_column('etat_avancement', 'nbPlaqNomNonInst')
    op.drop_column('etat_avancement', 'nbPlaqNomInst')
    op.drop_column('etat_avancement', 'entrPlaqNumInst')
    op.drop_column('etat_avancement', 'entrPlaqNumFab')
    op.drop_column('etat_avancement', 'entrPlaqNomInst')
    op.drop_column('etat_avancement', 'entrPlaqNomFab')
    # ### end Alembic commands ###
