"""empty message

Revision ID: 62eac5569cfc
Revises: 63f1dec73dd6
Create Date: 2021-02-18 14:22:48.037994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62eac5569cfc'
down_revision = '63f1dec73dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etat_avancement', sa.Column('date', sa.TIMESTAMP(), nullable=True))
    op.add_column('etat_avancement', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('etat_avancement', 'nbBaptAppr')
    op.drop_column('etat_avancement', 'pourcBaptAppr')
    op.drop_column('etat_avancement', 'pourcBapt')
    op.drop_column('etat_avancement', 'sommeEspPubBaptEtBaptAppr')
    op.drop_column('etat_avancement', 'pourcInstPlaqNum')
    op.drop_column('etat_avancement', 'pourcInstPlaqNom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etat_avancement', sa.Column('pourcInstPlaqNom', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('etat_avancement', sa.Column('pourcInstPlaqNum', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('etat_avancement', sa.Column('sommeEspPubBaptEtBaptAppr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('etat_avancement', sa.Column('pourcBapt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('etat_avancement', sa.Column('pourcBaptAppr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('etat_avancement', sa.Column('nbBaptAppr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('etat_avancement', 'status')
    op.drop_column('etat_avancement', 'date')
    # ### end Alembic commands ###
